### ISSUE TITLE
Fetching submodules fails (imgui_club)

### ISSUE THREAD

**Issue by close-paren** [tom-seddon/b2#13]
Currently unable to completely fetch b2 (using macOS 10.13.5, git version 2.15.2 (Apple Git-101.1)). Checking out submodules is failing with the following error:

```
error: Server does not allow request for unadvertised object a2150407befe6cd68d3b479b5714ebc5f129252d
Fetched in submodule path 'submodules/imgui_club', but it did not contain a2150407befe6cd68d3b479b5714ebc5f129252d. Direct fetching of that commit failed.
```

Is this known breakage from a WIP change (there were no issues before the most recent commit), or has something gone wrong? Thanks!

**Comment by tom-seddon** [comment]
Thanks for the report - this should be fixed now.

--Tom

P.S. What happened (as much for future me's benefit as anybody's): a submodule's history was rewritten, removing a commit that was previously referred to by the consuming repo, and this error message is git reporting this. It quite rightly checks for this when retrieving it as part of `git submodule update`. (This didn't affect the CI builds, I think because they retrieve the repo with `--depth=1` (or whatever) and so historical entries aren't checked.)
