### ISSUE TITLE
Debug version crashes with Emulate interlace

### ISSUE THREAD

**Issue by scraske** [tom-seddon/b2#144]
Selecting "Options" -> "Emulate interlace" causes an immediate crash with b2_Debug.

**Comment by scraske** [comment]
> Selecting "Options" -> "Emulate interlace" causes an immediate crash with b2_Debug.

Windows 10 2004, with NVIDIA 457.09 display drivers.

**Comment by rjpontefract** [comment]
This also causes an immediate abend on Mac OS 10.15.7 using B2 local build.  Here's the start of the problem report:

Process:               b2 [94804]

Path:                  /Applications/b2.app/Contents/MacOS/b2
Identifier:            com.tom-seddon.b2
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           b2 [94804]
User ID:               501

Date/Time:             2021-01-08 14:15:52.990 +1300
OS Version:            Mac OS X 10.15.7 (19H114)
Report Version:        12
Anonymous UUID:        D802F84B-7427-FB37-90C0-204D08BAB1AF


Time Awake Since Boot: 600000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00007fef8ceb5000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [94804]

VM Regions Near 0x7fef8ceb5000:
    MALLOC_LARGE           00007fef8ceb4000-00007fef8ceb5000 [    4K] rw-/rwx SM=PRV  
--> 
    MALLOC_MEDIUM          00007fef90000000-00007fef90800000 [ 8192K] rw-/rwx SM=PRV  

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.tom-seddon.b2             	0x000000010d4e5114 TVOutput::Update(VideoDataUnit const*, unsigned long) + 6276 (TVOutput.cpp:334)
1   com.tom-seddon.b2             	0x000000010d2e1b96 BeebWindow::UpdateTVTexture(BeebWindow::VBlankRecord*) + 374 (BeebWindow.cpp:1746)
2   com.tom-seddon.b2             	0x000000010d2e234a BeebWindow::HandleVBlank(unsigned long long) + 154 (BeebWindow.cpp:1934)
3   com.tom-seddon.b2             	0x000000010d2e4bf8 BeebWindow::HandleVBlank(VBlankMonitor*, void*, unsigned long long) + 200 (BeebWindow.cpp:2522)
4   com.tom-seddon.b2             	0x000000010d32aa6c BeebWindows::HandleVBlank(VBlankMonitor*, void*, unsigned long long) + 396 (BeebWindows.cpp:294)
5   com.tom-seddon.b2             	0x000000010d411d0d main2(int, char**, std::__1::shared_ptr<MessageList> const&) + 4429 (b2.cpp:1124)
6   com.tom-seddon.b2             	0x000000010d4109ae main + 62 (b2.cpp:1222)
7   libdyld.dylib                 	0x00007fff6e015cc9 start + 1

**Comment by tom-seddon** [comment]
Thanks for the report, and sorry about the crash.

If it'd be any consolation: emulated interlace looks absolutely awful. I only put it in there for comedy value 😅 (and this might explain the obvious lack of testing)

I'll hopefully be getting some time for more b2 work soon.

--Tom

**Comment by rjpontefract** [comment]
No problem, but now you’ve got me curious about how bad it looks :-)

**Comment by tom-seddon** [comment]
This seems to be working for me in the new release: https://github.com/tom-seddon/b2/releases/tag/b2-20210328-150259-a0b8957

Please let me know if you find otherwise.

Thanks,

--Tom
