### ISSUE TITLE
Help Adding a ROM (infinite Beeeep)

### ISSUE THREAD

**Issue by Ciava** [tom-seddon/b2#187]
Hello. Sorry for bothering. I know maybe this is not the right way to find help. 
I'd need to add roms for a BBC Master Compact Italian Clone (Olivetti Prodest PC 128S)

I never had a real Hardware but I'd like to emulate It on my Macbook M1. Please could you help me creating this Hardware?

I have 4 Roms:

ADFS210.rom
BASIC48.rom
OS51.rom
UTILS.rom

I tried to modify original Master 128 (MOS) configuration swapping roms with mine but I just get an infinite Beep!

Thanks for your help and sorry again if this is not the right place!

[pc128s_rom.zip](https://github.com/tom-seddon/b2/files/7611510/pc128s_rom.zip)

**Comment by tom-seddon** [comment]
Apologies for the delayed response. I'm afraid b2 doesn't support Master Compact yet, though it is on the list (and I do have one now for testing with): https://github.com/tom-seddon/b2/issues/14 - when I do this I'll try to make sure the Olivetti ROMs work too. I'm hopeful they'll be mostly the same as the standard Compact ones.

I'm not surprised to hear the ROMs don't work in Master 128 mode, as while the hardware is mostly the same there is at least one key difference (EEPROM rather than RTC). 

B-em (https://github.com/stardot/b-em) does support the Compact, but it doesn't seem to have a Mac version.

beebjit (https://github.com/scarybeasts/beebjit) can run the Compact ROMs, even though it doesn't support the hardware fully. It has an experimental Mac version, but you have to compile it yourself.

--Tom

**Comment by tom-seddon** [comment]
Closing this, as it is covered by #14.

--Tom
