### ISSUE TITLE
Pasting a long line (240 characters) results in a paste truncation error and an error beep

### ISSUE THREAD

**Issue by greenonline** [tom-seddon/b2#303]
Using latest release (`222352`). On Catalina 10.15.7

Copying this line from **TextEdit**  (242 characters)
```
1290 CR = 0: SR = 1:L=PO:V(L) = V(L) + 1: B=0:K=0:GOSUB 160:HOME=0:VDU30:PRINT:INVERSE=0:PRINT A$;: NORMAL=0: PRINT " ARRIVING "; L$(L);" AFTER": PRINT " A VOYAGE OF ";ET;" DAYS.": INVERSE=0:PRINT A$:NORMAL=0: GOSUB 780:HOME=0:VDU30:GOTO 120
```

and pasting into b2, results in a error beep and the end of the line missing (the `120` of the `GOTO 120` is missing):
```
1290 CR = 0: SR = 1:L=PO:V(L) = V(L) + 1: B=0:K=0:GOSUB 160:HOME=0:VDU30:PRINT:INVERSE=0:PRINT A$;: NORMAL=0: PRINT " ARRIVING "; L$(L);" AFTER": PRINT " A VOYAGE OF ";ET;" DAYS.": INVERSE=0:PRINT A$:NORMAL=0: GOSUB 780:HOME=0:VDU30:GOTO
```

If I remove the penultimate statement `VDU30:`, giving 236 characters,, like so:
```
1290 CR = 0: SR = 1:L=PO:V(L) = V(L) + 1: B=0:K=0:GOSUB 160:HOME=0:VDU30:PRINT:INVERSE=0:PRINT A$;: NORMAL=0: PRINT " ARRIVING "; L$(L);" AFTER": PRINT " A VOYAGE OF ";ET;" DAYS.": INVERSE=0:PRINT A$:NORMAL=0: GOSUB 780:HOME=0:GOTO 120
```
and paste that into b2, there is no error beep and the pasted line is complete and intact.

Paste using **Edit>OSRDCH Paste** menu option.

----

Narrowing it down, ***240 characters fails*** (using dummy variable `NORMAL1234`):
```
1290 CR = 0: SR = 1:L=PO:V(L) = V(L) + 1: B=0:K=0:GOSUB 160:HOME=0:VDU30:PRINT:INVERSE=0:PRINT A$;: NORMAL=0: PRINT " ARRIVING "; L$(L);" AFTER": PRINT " A VOYAGE OF ";ET;" DAYS.": INVERSE=0:PRINT A$:NORMAL1234=0: GOSUB 780:HOME=0:GOTO 120
```
whereas this ***239 character paste works***  (using dummy variable `NORMAL123` (one less character))
```
1290 CR = 0: SR = 1:L=PO:V(L) = V(L) + 1: B=0:K=0:GOSUB 160:HOME=0:VDU30:PRINT:INVERSE=0:PRINT A$;: NORMAL=0: PRINT " ARRIVING "; L$(L);" AFTER": PRINT " A VOYAGE OF ";ET;" DAYS.": INVERSE=0:PRINT A$:NORMAL123=0: GOSUB 780:HOME=0:GOTO 120
```

Note that, as a comparison, the longer version of the line pastes in correctly when using BeebEm5.

**Comment by greenonline** [comment]
Just realised that BeebEm5 also fails on this line and that it is probably a limitation of BBC BASIC line length.

**Comment by tom-seddon** [comment]
Thanks for the report. I don't know offhand what line length limit is, but 240 doesn't sound surprising. I vaguely remember there being a few bytes of workspace at the end of the page that BASIC uses as an input buffer.

The general paste option will probably always remain a way of sending an endless stream of keypresses, but the Paste BASIC option, which is specifically there for BASIC programs, should probably do a quick check of the clipboard contents and highlight this issue (along with any others that prove worth checking for...) ahead of time.

(At the moment, from memory, all it does is ensure the text ends with a newline, so that you don't end up with a buffered-up line at the end that means you have to press RETURN.)
