### ISSUE TITLE
Ugly scaling on first startup

### ISSUE THREAD

**Issue by SteveFosdick** [tom-seddon/b2#4]
This is a bit similar to this issue raised on B-E-m: https://github.com/stardot/b-em/issues/56

When I first start b2 the width of the horizontal lines of the font is not consistent as per this screenshot:

![screenshot from 2018-04-09 15-06-15](https://user-images.githubusercontent.com/1048671/38502787-40123d42-3c08-11e8-8719-1e374a9f2388.png)

It looks like this might be caused by the emulated BBC's screen being scaled down to fit in the window because if I expand the window vertically it resolves:

![screenshot from 2018-04-09 15-07-15](https://user-images.githubusercontent.com/1048671/38502920-a4441b28-3c08-11e8-99c2-8e3776355489.png)

As this seems to be peculiar to the vertical direction I wonder if you are, perhaps, calculating the initial; window size to allow 1:1 and then having some of the vertical space stolen by the menu?

Interesting, BTW, that you have taken the opposite approach to scaling from the one I took in the Allegro 5 port of B-Em.  B-Em only every scales up - if you make the window too small it crops instead.  b2 appears to only ever scale down.

**Comment by tom-seddon** [comment]
Yes, good spot - the window should probably start out a bit larger to accommodate the menu bar. I have to say I rather assumed everybody would maximize it or make it half the screen :)

Regarding the scaling, it should scale both up and down, but it does preserve the aspect ratio so you can end up with additional borders.

--Tom

P.S. If you built it from the repo, when you run a debug build you can tick `Test pattern` in the options to see the area used for the BBC display.

**Comment by tom-seddon** [comment]
I did two fixes for this: make the window a better size, and have filtering on by default.

Unfiltered output probably isn't very useful any more, since by default the emulator applies a horizontal scale factor of ~0.94 to get the correct aspect ratio. That'll never produce pixel-perfect output...

Things still aren't 100% right; I think the gui layout mechanism may be getting a mite confused by some of the stuff I'm doing, and/or I'm doing it wrong anyway. But if you start up with no b2.json it now looks quite a bit better.

--Tom

**Comment by tom-seddon** [comment]
Fixed by https://github.com/tom-seddon/b2/commit/0e1f9b7d48272f3626dba606ed81aa563abd64b7.

--Tom
